config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      users/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#        user_registration POST   /users(.:format)               users/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#                          PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                   styles GET    /styles(.:format)              styles#index
#                          POST   /styles(.:format)              styles#create
#                new_style GET    /styles/new(.:format)          styles#new
#               edit_style GET    /styles/:id/edit(.:format)     styles#edit
#                    style GET    /styles/:id(.:format)          styles#show
#                          PATCH  /styles/:id(.:format)          styles#update
#                          PUT    /styles/:id(.:format)          styles#update
#                          DELETE /styles/:id(.:format)          styles#destroy
#                     root GET    /                              pages#home
#               hypertexts GET    /hypertexts(.:format)          hypertexts#index
#                          POST   /hypertexts(.:format)          hypertexts#create
#            new_hypertext GET    /hypertexts/new(.:format)      hypertexts#new
#           edit_hypertext GET    /hypertexts/:id/edit(.:format) hypertexts#edit
#                hypertext GET    /hypertexts/:id(.:format)      hypertexts#show
#                          PATCH  /hypertexts/:id(.:format)      hypertexts#update
#                          PUT    /hypertexts/:id(.:format)      hypertexts#update
#                          DELETE /hypertexts/:id(.:format)      hypertexts#destroy
#       hypertexts_find_by GET    /hypertexts/find_by(.:format)  hypertexts#find_by
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :styles
  root to: "pages#home"

  # get '/users/sign_out', to: 'devise/sessions#destroy'

  resources :hypertexts
  put 'finderID' => 'hypertexts#find_by'
  

end

app/models/hypertext.rb
# == Schema Information
#
# Table name: hypertexts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Hypertext < ActiveRecord::Base
  belongs_to :user
end

app/controllers/hypertexts_controller.rb
# == Schema Information
#
# Table name: hypertexts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class HypertextsController < ApplicationController
  before_action :set_hypertext, only: [:show, :edit, :update, :destroy]

  # GET /hypertexts
  # GET /hypertexts.json
  def index
    @hypertexts = Hypertext.all
  end

  # GET /hypertexts/1
  # GET /hypertexts/1.json
  def show
  end

  # GET /hypertexts/new
  def new
    @hypertext = Hypertext.new
  end

  # GET /hypertexts/1/edit
  def edit
  end

  # POST /hypertexts
  # POST /hypertexts.json
  def create
    @hypertext = Hypertext.new(hypertext_params)

    respond_to do |format|
      if @hypertext.save
        format.html { redirect_to @hypertext, notice: 'Hypertext was successfully created.' }
        format.json { render :show, status: :created, location: @hypertext }
      else
        format.html { render :new }
        format.json { render json: @hypertext.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hypertexts/1
  # PATCH/PUT /hypertexts/1.json
  def update
    respond_to do |format|
      if @hypertext.update(hypertext_params)
        format.html { redirect_to @hypertext, notice: 'Hypertext was successfully updated.' }
        format.json { render :show, status: :ok, location: @hypertext }
      else
        format.html { render :edit }
        format.json { render json: @hypertext.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hypertexts/1
  # DELETE /hypertexts/1.json
  def destroy
    @hypertext.destroy
    respond_to do |format|
      format.html { redirect_to hypertexts_url, notice: 'Hypertext was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find_by
    return render json: Hypertext.where({user_id: params[:individual]})
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hypertext
      @hypertext = Hypertext.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hypertext_params
      params.require(:hypertext).permit(:user_id, :content)
    end
end

app/helpers/hypertexts_helper.rb
# == Schema Information
#
# Table name: hypertexts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module HypertextsHelper
end

app/views/hypertexts/_form.html.erb
<%= form_for(@hypertext) do |f| %>
  <% if @hypertext.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hypertext.errors.count, "error") %> prohibited this hypertext from being saved:</h2>

      <ul>
      <% @hypertext.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hypertexts/edit.html.erb
<h1>Editing Hypertext</h1>

<%= render 'form' %>

<%= link_to 'Show', @hypertext %> |
<%= link_to 'Back', hypertexts_path %>

app/views/hypertexts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hypertexts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hypertexts.each do |hypertext| %>
      <tr>
        <td><%= hypertext.user_id %></td>
        <td><%= hypertext.content %></td>
        <td><%= link_to 'Show', hypertext %></td>
        <td><%= link_to 'Edit', edit_hypertext_path(hypertext) %></td>
        <td><%= link_to 'Destroy', hypertext, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hypertext', new_hypertext_path %>

app/views/hypertexts/new.html.erb
<h1>New Hypertext</h1>

<%= render 'form' %>

<%= link_to 'Back', hypertexts_path %>

app/views/hypertexts/show.html.erb
<%== @hypertext.content %>


<div id="hypertextDropdown" class="notDropped">
  
  <% if current_user %>
    <div id="hyperLinks" class="nav button">V</div>
  <% else %>
    <div id="hyperLinks" class="nav button hidden">V</div>
  <% end %>

  <div id="staticLink">
    HTML
  </div>

  <div id="hyperLists" class="button nav hidden">
    
  </div>
 
  <% if @hypertext.user == current_user %>
    <textarea id="txt" class="inv">
      <%= @hypertext.content %>
    </textarea>
  <% else %>
    <textarea id="txt" class="inv">
      <%= @hypertext.content %>
    </textarea>
  <% end %>

</div>

  <% if @hypertext.user == current_user %>
    <div class="button nav save" id="savesies">SAVE!</div>
  <% end %>



<!-- <div class="button">Grab me some JSON!</div> -->
<div id="userPage">
  <div id="hello">

  </div>
</div>

<div class="hypertext">

</div>

<div class="style"></div>

<div id="HIDE"><% if current_user %><%= "#{current_user.id}" %><% end %></div>
<div id="arrows"></div>

<div id="tutDown">
  <div id="tutorialBox" class="tutNotDropped">
      <div id="menu">Menu</div>

    <div class="tutorialText"></div>
    <div id="tutorialBTN">
      Tutorial
    </div>
  </div>
</div>